#
# (C) Copyright 2007-2010
# Hu Chunlin <chunlin.hu@gmail.com>
#
# Makefile - To make my life easier.
#

ifeq ($(BOARDTYPE),XSCB_V2)
SUBDIRS = oicdrv oiclib oicapp cascade sgfpapp sdhapp gfpapp
else
SUBDIRS = oicdrv oiclib oicapp cascade sgfpapp
endif

include $(CURDIR)/../dirs.mk

