/*
 *
 * pktcmdhdl.h - A brief description to describe this file.
 *
 */

#ifndef _HEAD_PKTCMDHDL_4F4F7F39_2990E679_2B8BE289_H
#define _HEAD_PKTCMDHDL_4F4F7F39_2990E679_2B8BE289_H

#include "pktcmd.h"
#include "pktcmdinfo.h"

extern struct pktcmd_cb_map pktcmd_cbs[];

#define PROTOTYPE_PKTCMDHDL(cmdname) \
extern int Cmd##cmdname##Hdl(void *devhd, pktcmd_devcallback devcmdhd, \
		struct pktcmd_cmdinfo *cmd, unsigned char *arg, int len)

#define PROTOTYPE_PKTCMDACKHDL(cmdname) \
extern int Cmd##cmdname##ACKHdl(void *devhd, pktcmd_devcallback devcmdhd, \
		struct pktcmd_cmdinfo *cmd, unsigned char *arg, int len)

#if defined(__cplusplus)
extern "C" {
#endif

PROTOTYPE_PKTCMDHDL(GetHwModel);
PROTOTYPE_PKTCMDHDL(GetHwVersion);
PROTOTYPE_PKTCMDHDL(GetSwVersion);
PROTOTYPE_PKTCMDHDL(GetHwSerialNum);
PROTOTYPE_PKTCMDHDL(GetHwDescription);
PROTOTYPE_PKTCMDHDL(SetHwDescription);
PROTOTYPE_PKTCMDHDL(GetEtherInfo);
PROTOTYPE_PKTCMDHDL(SetEtherInfo);
PROTOTYPE_PKTCMDHDL(GetMac);
PROTOTYPE_PKTCMDHDL(SetMac);
PROTOTYPE_PKTCMDHDL(GetServerIp);
PROTOTYPE_PKTCMDHDL(SetServerIp);
PROTOTYPE_PKTCMDHDL(GetGatewayIp);
PROTOTYPE_PKTCMDHDL(SetGatewayIp);
PROTOTYPE_PKTCMDHDL(GetSysTime);
PROTOTYPE_PKTCMDHDL(SetSysTime);
PROTOTYPE_PKTCMDHDL(GetNtpMode);
PROTOTYPE_PKTCMDHDL(SetNtpMode);
PROTOTYPE_PKTCMDHDL(GetClkType);
PROTOTYPE_PKTCMDHDL(SetClkType);
PROTOTYPE_PKTCMDHDL(GetPorts);
PROTOTYPE_PKTCMDHDL(GetGlobalPortCfg);
PROTOTYPE_PKTCMDHDL(SetGlobalPortCfg);
PROTOTYPE_PKTCMDHDL(GetPortCfg);
PROTOTYPE_PKTCMDHDL(SetPortCfg);
PROTOTYPE_PKTCMDHDL(DelPortCfg);
PROTOTYPE_PKTCMDHDL(DownloadPortCfgFile);
PROTOTYPE_PKTCMDHDL(UploadPortCfgFile);
PROTOTYPE_PKTCMDHDL(DownloadChCfgFile);
PROTOTYPE_PKTCMDHDL(UploadChCfgFile);
PROTOTYPE_PKTCMDHDL(GetDevId);
PROTOTYPE_PKTCMDHDL(SetDevId);
PROTOTYPE_PKTCMDHDL(GetPackType);
PROTOTYPE_PKTCMDHDL(SetPackType);
PROTOTYPE_PKTCMDHDL(GetDevMode);
PROTOTYPE_PKTCMDHDL(SetDevMode);
PROTOTYPE_PKTCMDHDL(GetPortSdhMatrixCfg);
PROTOTYPE_PKTCMDHDL(SetPortSdhMatrixCfg);
PROTOTYPE_PKTCMDHDL(GetPortMatrixCfg);
PROTOTYPE_PKTCMDHDL(SetPortMatrixCfg);
PROTOTYPE_PKTCMDHDL(DownloadMatrixCfgFile);
PROTOTYPE_PKTCMDHDL(UploadMatrixCfgFile);
PROTOTYPE_PKTCMDHDL(GainScan);
PROTOTYPE_PKTCMDHDL(ChanScan);
PROTOTYPE_PKTCMDHDL(GetGlobalBertCfg);
PROTOTYPE_PKTCMDHDL(SetGlobalBertCfg);
PROTOTYPE_PKTCMDHDL(GetBertCfg);
PROTOTYPE_PKTCMDHDL(SetBertCfg);
PROTOTYPE_PKTCMDHDL(DelBertCfg);
PROTOTYPE_PKTCMDHDL(StartPrbs);
PROTOTYPE_PKTCMDHDL(StopPrbs);
PROTOTYPE_PKTCMDHDL(InsertError);
PROTOTYPE_PKTCMDHDL(SysReboot);
PROTOTYPE_PKTCMDHDL(SysFirmwareUpgrade);
PROTOTYPE_PKTCMDHDL(GetSysResRep);
PROTOTYPE_PKTCMDHDL(GetLineStatInfo);
PROTOTYPE_PKTCMDHDL(ClrLineStatInfo);
PROTOTYPE_PKTCMDHDL(GetPortStatInfo);
PROTOTYPE_PKTCMDHDL(ClrPortStatInfo);
PROTOTYPE_PKTCMDHDL(StartPfmTest);
PROTOTYPE_PKTCMDHDL(GetPortPfmResult);
PROTOTYPE_PKTCMDHDL(StopPfmTest);
PROTOTYPE_PKTCMDHDL(GetChCfg);
PROTOTYPE_PKTCMDHDL(GetChStatInfo);
PROTOTYPE_PKTCMDHDL(ClrChStatInfo);
PROTOTYPE_PKTCMDHDL(GetRawData);
PROTOTYPE_PKTCMDHDL(GetRtVoice);
PROTOTYPE_PKTCMDHDL(GetCallTrace);

PROTOTYPE_PKTCMDACKHDL(GetHwModel);
PROTOTYPE_PKTCMDACKHDL(GetHwVersion);
PROTOTYPE_PKTCMDACKHDL(GetSwVersion);
PROTOTYPE_PKTCMDACKHDL(GetHwSerialNum);
PROTOTYPE_PKTCMDACKHDL(GetHwDescription);
PROTOTYPE_PKTCMDACKHDL(SetHwDescription);
PROTOTYPE_PKTCMDACKHDL(GetEtherInfo);
PROTOTYPE_PKTCMDACKHDL(SetEtherInfo);
PROTOTYPE_PKTCMDACKHDL(GetMac);
PROTOTYPE_PKTCMDACKHDL(SetMac);
PROTOTYPE_PKTCMDACKHDL(GetServerIp);
PROTOTYPE_PKTCMDACKHDL(SetServerIp);
PROTOTYPE_PKTCMDACKHDL(GetGatewayIp);
PROTOTYPE_PKTCMDACKHDL(SetGatewayIp);
PROTOTYPE_PKTCMDACKHDL(GetSysTime);
PROTOTYPE_PKTCMDACKHDL(SetSysTime);
PROTOTYPE_PKTCMDACKHDL(GetNtpMode);
PROTOTYPE_PKTCMDACKHDL(SetNtpMode);
PROTOTYPE_PKTCMDACKHDL(GetClkType);
PROTOTYPE_PKTCMDACKHDL(SetClkType);
PROTOTYPE_PKTCMDACKHDL(GetPorts);
PROTOTYPE_PKTCMDACKHDL(GetGlobalPortCfg);
PROTOTYPE_PKTCMDACKHDL(SetGlobalPortCfg);
PROTOTYPE_PKTCMDACKHDL(GetPortCfg);
PROTOTYPE_PKTCMDACKHDL(SetPortCfg);
PROTOTYPE_PKTCMDACKHDL(DelPortCfg);
PROTOTYPE_PKTCMDACKHDL(DownloadPortCfgFile);
PROTOTYPE_PKTCMDACKHDL(UploadPortCfgFile);
PROTOTYPE_PKTCMDACKHDL(DownloadChCfgFile);
PROTOTYPE_PKTCMDACKHDL(UploadChCfgFile);
PROTOTYPE_PKTCMDACKHDL(GetDevId);
PROTOTYPE_PKTCMDACKHDL(SetDevId);
PROTOTYPE_PKTCMDACKHDL(GetPackType);
PROTOTYPE_PKTCMDACKHDL(SetPackType);
PROTOTYPE_PKTCMDACKHDL(GetDevMode);
PROTOTYPE_PKTCMDACKHDL(SetDevMode);
PROTOTYPE_PKTCMDACKHDL(GetPortSdhMatrixCfg);
PROTOTYPE_PKTCMDACKHDL(SetPortSdhMatrixCfg);
PROTOTYPE_PKTCMDACKHDL(GetPortMatrixCfg);
PROTOTYPE_PKTCMDACKHDL(SetPortMatrixCfg);
PROTOTYPE_PKTCMDACKHDL(DownloadMatrixCfgFile);
PROTOTYPE_PKTCMDACKHDL(UploadMatrixCfgFile);
PROTOTYPE_PKTCMDACKHDL(GainScan);
PROTOTYPE_PKTCMDACKHDL(ChanScan);
PROTOTYPE_PKTCMDACKHDL(GetGlobalBertCfg);
PROTOTYPE_PKTCMDACKHDL(SetGlobalBertCfg);
PROTOTYPE_PKTCMDACKHDL(GetBertCfg);
PROTOTYPE_PKTCMDACKHDL(SetBertCfg);
PROTOTYPE_PKTCMDACKHDL(DelBertCfg);
PROTOTYPE_PKTCMDACKHDL(StartPrbs);
PROTOTYPE_PKTCMDACKHDL(StopPrbs);
PROTOTYPE_PKTCMDACKHDL(InsertError);
PROTOTYPE_PKTCMDACKHDL(SysReboot);
PROTOTYPE_PKTCMDACKHDL(SysFirmwareUpgrade);
PROTOTYPE_PKTCMDACKHDL(GetSysResRep);
PROTOTYPE_PKTCMDACKHDL(GetLineStatInfo);
PROTOTYPE_PKTCMDACKHDL(ClrLineStatInfo);
PROTOTYPE_PKTCMDACKHDL(GetPortStatInfo);
PROTOTYPE_PKTCMDACKHDL(ClrPortStatInfo);
PROTOTYPE_PKTCMDACKHDL(StartPfmTest);
PROTOTYPE_PKTCMDACKHDL(GetPortPfmResult);
PROTOTYPE_PKTCMDACKHDL(StopPfmTest);
PROTOTYPE_PKTCMDACKHDL(GetChCfg);
PROTOTYPE_PKTCMDACKHDL(GetChStatInfo);
PROTOTYPE_PKTCMDACKHDL(ClrChStatInfo);
PROTOTYPE_PKTCMDACKHDL(GetRawData);
PROTOTYPE_PKTCMDACKHDL(GetRtVoice);
PROTOTYPE_PKTCMDACKHDL(GetCallTrace);

#if defined(__cplusplus)
}
#endif

#endif /* #ifndef _HEAD_PKTCMDHDL_4F4F7F39_2990E679_2B8BE289_H */
