/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef BOARDSINFOTABLE_H
#define BOARDSINFOTABLE_H

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nm_glb.h"

/* function declarations */
void init_boardsInfoTable(void);
void exit_boardsInfoTable(void);
void initialize_table_boardsInfoTable(void);
int boardsInfoTable_reset_valid(void);
int boardsInfoTable_update(struct nmboard_info *bdinfo);
void boardsInfoTable_delete_invalid(void);
int boardsInfoTable_getbdtype(struct nm_lkaddr_info po, int *bdtype);
int boardsInfoTable_getboards(int bdtype, struct nm_lkaddr_info *po);
void boardsInfoTable_proc_send_req(void);
void boardsInfoTable_clear(void);
Netsnmp_Node_Handler boardsInfoTable_handler;
Netsnmp_First_Data_Point  boardsInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point   boardsInfoTable_get_next_data_point;

/* column number definitions for table boardsInfoTable */
       #define COLUMN_BOARDRACK		1
       #define COLUMN_BOARDSHELF		2
       #define COLUMN_BOARDSLOT		3
       #define COLUMN_BOARDSUBSLOT		4
       #define COLUMN_BOARDTYPE		5
       #define COLUMN_BOARDSTAT		6
#endif /* BOARDSINFOTABLE_H */
