/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "os.h"
#include "aplog.h"
#include "bdtype.h"
#include "nm_typdef.h"
#include "nmpkt.h"
#include "mutex.h"
#include "nm_glb.h"
#include "snmpcommon.h"
#include "socketAdapt.h"
#include "boardsInfoTable.h"

    /* Typical data structure for a row entry */
struct boardsInfoTable_entry {
    /* Index values */
    long boardRack;
    long boardShelf;
    long boardSlot;
    long boardSubSlot;

    /* Column values */
    long boardType;
    long boardStat;

    /* Illustrate using a simple linked list */
    int   valid;
    struct boardsInfoTable_entry *next;
};

struct boardsInfoTable_entry  *boardsInfoTable_head = NULL;
static int boardsInfoTable_count = 0;
static void *lstlock = NULL;

/** Initializes the boardsInfoTable module */
void
init_boardsInfoTable(void)
{
	lstlock = mutex_open(NULL);
	if (lstlock == NULL) {
		LOGERROR("%s: mutex_open failed", __func__);
		return;
	}
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_boardsInfoTable();
}

void exit_boardsInfoTable(void)
{
	boardsInfoTable_clear();

	if (lstlock) 
		mutex_close(lstlock);
}

/** Initialize the boardsInfoTable table by defining its contents and how it's structured */
void
initialize_table_boardsInfoTable(void)
{
    const oid boardsInfoTable_oid[] = {1,3,6,1,4,1,8990,1,2,1};
    const size_t boardsInfoTable_oid_len   = OID_LENGTH(boardsInfoTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("boardsInfoTable:init", "initializing table boardsInfoTable\n"));

    reg = netsnmp_create_handler_registration(
              "boardsInfoTable",     boardsInfoTable_handler,
              boardsInfoTable_oid, boardsInfoTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: boardRack */
                           ASN_INTEGER,  /* index: boardShelf */
                           ASN_INTEGER,  /* index: boardSlot */
                           ASN_INTEGER,  /* index: boardSubSlot */
                           0);
    table_info->min_column = COLUMN_BOARDRACK;
    table_info->max_column = COLUMN_BOARDSTAT;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = boardsInfoTable_get_first_data_point;
    iinfo->get_next_data_point  = boardsInfoTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

/* create a new row in the (unsorted) table */
struct boardsInfoTable_entry *
boardsInfoTable_createEntry( long  boardRack, long  boardShelf,
                 long  boardSlot, long  boardSubSlot) 
{
    struct boardsInfoTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct boardsInfoTable_entry);
    if (!entry)
        return NULL;

    entry->boardRack = boardRack;
    entry->boardShelf = boardShelf;
    entry->boardSlot = boardSlot;
    entry->boardSubSlot = boardSubSlot;
    entry->next = boardsInfoTable_head;
    boardsInfoTable_head = entry;
	boardsInfoTable_count++;

    return entry;
}

/* remove a row from the table */
void
boardsInfoTable_removeEntry( struct boardsInfoTable_entry *entry ) {
    struct boardsInfoTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = boardsInfoTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        boardsInfoTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
	boardsInfoTable_count--;
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
boardsInfoTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = boardsInfoTable_head;
    return boardsInfoTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
boardsInfoTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct boardsInfoTable_entry *entry = (struct boardsInfoTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

	mutex_lock(lstlock);
    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->boardRack );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->boardShelf );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->boardSlot );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->boardSubSlot );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
		mutex_unlock(lstlock);
        return put_index_data;
    } else {
		mutex_unlock(lstlock);
        return NULL;
    }
}

int boardsInfoTable_reset_valid(void) {
	struct boardsInfoTable_entry *entry = boardsInfoTable_head;

	if (!entry)
		return 0;

	mutex_lock(lstlock);
	while (entry) {
		entry->valid = 0;
		entry = entry->next;
	}
	mutex_unlock(lstlock);

	return 0;
}

int boardsInfoTable_update(struct nmboard_info *bdinfo) {
	struct boardsInfoTable_entry *entry = boardsInfoTable_head;

	if (!bdinfo)
		return -1;

	mutex_lock(lstlock);
	while (entry) {
		if ((entry->boardRack == bdinfo->rack) && 
				(entry->boardShelf == bdinfo->shelf) && 
				(entry->boardSlot == bdinfo->slot) &&
				(entry->boardSubSlot == bdinfo->subslot)) {
			entry->boardType = bdinfo->bdtype;
			entry->boardStat = bdinfo->stat;
			entry->valid = 1;
			mutex_unlock(lstlock);
			return 0;
		}
		entry = entry->next;
	}

	entry = boardsInfoTable_createEntry(bdinfo->rack, 
			bdinfo->shelf, bdinfo->slot, bdinfo->subslot);
	if (!entry) {
		mutex_unlock(lstlock);
		return -1;
	}
	
	entry->boardType = bdinfo->bdtype;
	entry->boardStat = bdinfo->stat;
	entry->valid = 1;

	mutex_unlock(lstlock);
	return 0;
}

DEFINE_TABLE_ENTRY_DELETE_INVALID_FUNC(boardsInfoTable) 

void boardsInfoTable_delete_invalid(void) 
{
	mutex_lock(lstlock);

	boardsInfoTable_head = boardsInfoTable_del_invalid_entrys(boardsInfoTable_head);

	mutex_unlock(lstlock);
}

int boardsInfoTable_getbdtype(struct nm_lkaddr_info po, int *bdtype) {
	struct boardsInfoTable_entry *entry = boardsInfoTable_head;

	if (!bdtype)
		return -1;

	mutex_lock(lstlock);
	while (entry) {
		if ((entry->boardRack == po.rack) && 
				(entry->boardShelf == po.shelf) && 
				(entry->boardSlot == po.slot) &&
				(entry->boardSubSlot == po.subslot)) {
			*bdtype = entry->boardType;
			mutex_unlock(lstlock);
			return 0;
		}
		entry = entry->next;
	}

	mutex_unlock(lstlock);
	return -1;
}

int boardsInfoTable_getboards(int bdtype, struct nm_lkaddr_info *po) {
	struct boardsInfoTable_entry *entry = boardsInfoTable_head;
	int i = 0;

	if (!po)
		return 0;

	mutex_lock(lstlock);
	while (entry) {
		if (entry->boardType == bdtype) {
			po[i].rack = entry->boardRack;
			po[i].shelf = entry->boardShelf;
			po[i].slot = entry->boardSlot;
			po[i].subslot = entry->boardSubSlot;
			i++;
			if (i >= SNMP_MAX_BOARD_CNT) {
				LOGERROR("%s: boards over the max num", __func__, i);
				return 0;
			}
		}
		entry = entry->next;
	}

	mutex_unlock(lstlock);

	return i;
}

void boardsInfoTable_clear(void) 
{
	mutex_lock(lstlock);

	while (boardsInfoTable_head) {
		boardsInfoTable_removeEntry(boardsInfoTable_head);
	}
	
	boardsInfoTable_head = NULL;
	boardsInfoTable_count = 0;

	mutex_unlock(lstlock);
}

void boardsInfoTable_proc_send_req(void) {
	struct boardsInfoTable_entry *entry = boardsInfoTable_head;
	uint8_t buf[64];
	int dlen = 0;

	mutex_lock(lstlock);

	while (entry) {
		buf[0] = entry->boardRack;
		buf[1] = entry->boardShelf;
		buf[2] = entry->boardSlot;
		buf[3] = entry->boardSubSlot;

		if (entry->boardType == BOARD_TYPE_MPCB_V3 || 
				entry->boardType == BOARD_TYPE_MACB_V2) {
			dlen = 4;
			socketAdapt_send_cmd_req(NM_MODULE_SWITCH, NM_CMD_GET_SW_PORT_STATUS, buf, dlen);
		}
		else if (entry->boardType == BOARD_TYPE_EIPB_V2) {
			dlen = 4;
			socketAdapt_send_cmd_req(NM_MODULE_E1PHY, NM_CMD_GET_E1PHY_STATUS, buf, dlen);
#if 0
			socketAdapt_send_cmd_req(NM_MODULE_SWITCH, NM_CMD_GET_SW_PORT_STATUS, buf, dlen);
			buf[4] = 1; /* fpgaid */
			buf[5] = 1; /* fpga type: E1PHY */
			dlen = 6;
			socketAdapt_send_cmd_req(NM_MODULE_FPGA, NM_CMD_GET_FPGA_STAT, buf, dlen);
			socketAdapt_send_cmd_req(NM_MODULE_FPGA, NM_CMD_GET_FPGA_FLOW_STAT, buf, dlen);
		}
		else if (entry->boardType == BOARD_TYPE_EI_AMC_V1) {
			dlen = 4;
			socketAdapt_send_cmd_req(NM_MODULE_E1PHY, NM_CMD_GET_E1PHY_STATUS, buf, dlen);
		}
		else if (entry->boardType == BOARD_TYPE_OI_AMC_V3) {
			buf[4] = 1; /* fpgaid */
			buf[5] = 2; /* fpga type: OI collect */
			dlen = 6;
			socketAdapt_send_cmd_req(NM_MODULE_FPGA, NM_CMD_GET_FPGA_STATUS, buf, dlen);
			socketAdapt_send_cmd_req(NM_MODULE_FPGA, NM_CMD_GET_FPGA_FLOW_STAT, buf, dlen);
#endif
		}
		else {
			LOGERROR("unknown bdtype %ld", entry->boardType);
		}
		entry = entry->next;
	}

	mutex_unlock(lstlock);
}

/** handles requests for the boardsInfoTable table */
int
boardsInfoTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct boardsInfoTable_entry          *table_entry;

    DEBUGMSGTL(("boardsInfoTable:handler", "Processing request (%d)\n", reqinfo->mode));

	mutex_lock(lstlock);
    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct boardsInfoTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            if ( !table_entry ) {
                continue;
            }

            switch (table_info->colnum) {
            case COLUMN_BOARDRACK:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardRack);
                break;
            case COLUMN_BOARDSHELF:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardShelf);
                break;
            case COLUMN_BOARDSLOT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardSlot);
                break;
            case COLUMN_BOARDSUBSLOT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardSubSlot);
                break;
            case COLUMN_BOARDTYPE:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardType);
                break;
            case COLUMN_BOARDSTAT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->boardStat);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
	mutex_unlock(lstlock);

    return SNMP_ERR_NOERROR;
}

