/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "os.h"
#include "aplog.h"
#include "bdtype.h"
#include "mutex.h"
#include "nm_typdef.h"
#include "nm_glb.h"
#include "nmpkt.h"
#include "snmpcommon.h"
#include "phyadapt.h"
#include "snmpMibModule.h"
#include "boardsInfoTable.h"
#include "e1PhyMibPortInfoAlarmTable.h"

    /* Typical data structure for a row entry */
struct e1PhyMibPortInfoAlarmTable_entry {
    /* Index values */
    in_addr_t e1PhyMibPortInfoAlarmTablePosition;
    long e1PhyMibPortInfoAlarmTablePort;
    long e1PhyMibPortInfoAlarmTableE1Port;

    /* Column values */
    long e1PhyMibPortInfoAlarmTableLOS;
    long e1PhyMibPortInfoAlarmTableLOF;
    long e1PhyMibPortInfoAlarmTableAIS;
    long e1PhyMibPortInfoAlarmTableRAI;
    long e1PhyMibPortInfoAlarmTableCASMFLOSS;
    long e1PhyMibPortInfoAlarmTableCRCMFLOSS;
    long e1PhyMibPortInfoAlarmTableCASMFRAI;
    long e1PhyMibPortInfoAlarmTableOEQ;
    long e1PhyMibPortInfoAlarmTableUEQ;
    long e1PhyMibPortInfoAlarmTableJALT;
    long e1PhyMibPortInfoAlarmTableRESF;
    long e1PhyMibPortInfoAlarmTableRESEM;
    long e1PhyMibPortInfoAlarmTableRSLIP;
    long e1PhyMibPortInfoAlarmTableRSL;
    long e1PhyMibPortInfoAlarmTableTOC;
    long e1PhyMibPortInfoAlarmTableTSC;
    u_long e1PhyMibPortInfoAlarmTableCODE;
    u_long e1PhyMibPortInfoAlarmTableCRC;
    u_long e1PhyMibPortInfoAlarmTableFAS;
    u_long e1PhyMibPortInfoAlarmTableEBIT;

    /* Illustrate using a simple linked list */
    int   valid;
    struct e1PhyMibPortInfoAlarmTable_entry *next;
};

struct e1PhyMibPortInfoAlarmTable_entry  *e1PhyMibPortInfoAlarmTable_head = NULL;
static void *lstlock = NULL;
static int e1PhyMibPortInfoAlarmTable_count = 0;

/** Initializes the e1PhyMibPortInfoAlarmTable module */
void init_e1PhyMibPortInfoAlarmTable(void)
{
	lstlock = mutex_open(NULL);
	if (lstlock == NULL) {
		LOGERROR("%s: mutex_open failed", __func__);
		return;
	}
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_e1PhyMibPortInfoAlarmTable();
}

void exit_e1PhyMibPortInfoAlarmTable(void)
{
	e1PhyMibPortInfoAlarmTable_clear();

	if (lstlock) 
		mutex_close(lstlock);
}

/** Initialize the e1PhyMibPortInfoAlarmTable table by defining its contents and how it's structured */
void initialize_table_e1PhyMibPortInfoAlarmTable(void)
{
    const oid e1PhyMibPortInfoAlarmTable_oid[] = {1,3,6,1,4,1,8990,1,3,1};
    const size_t e1PhyMibPortInfoAlarmTable_oid_len   = OID_LENGTH(e1PhyMibPortInfoAlarmTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("e1PhyMibPortInfoAlarmTable:init", "initializing table e1PhyMibPortInfoAlarmTable\n"));

    reg = netsnmp_create_handler_registration(
              "e1PhyMibPortInfoAlarmTable",     e1PhyMibPortInfoAlarmTable_handler,
              e1PhyMibPortInfoAlarmTable_oid, e1PhyMibPortInfoAlarmTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_IPADDRESS,  /* index: e1PhyMibPortInfoAlarmTablePosition */
                           ASN_INTEGER,  /* index: e1PhyMibPortInfoAlarmTablePort */
                           ASN_INTEGER,  /* index: e1PhyMibPortInfoAlarmTableE1Port */
                           0);
    table_info->min_column = COLUMN_E1PHYMIBPORTINFOALARMTABLEPOSITION;
    table_info->max_column = COLUMN_E1PHYMIBPORTINFOALARMTABLEEBIT;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = e1PhyMibPortInfoAlarmTable_get_first_data_point;
    iinfo->get_next_data_point  = e1PhyMibPortInfoAlarmTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

/* create a new row in the (unsorted) table */
struct e1PhyMibPortInfoAlarmTable_entry *
e1PhyMibPortInfoAlarmTable_createEntry(
                 in_addr_t  e1PhyMibPortInfoAlarmTablePosition,
                 long  e1PhyMibPortInfoAlarmTablePort,
                 long  e1PhyMibPortInfoAlarmTableE1Port) {
    struct e1PhyMibPortInfoAlarmTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct e1PhyMibPortInfoAlarmTable_entry);
    if (!entry)
        return NULL;

    entry->e1PhyMibPortInfoAlarmTablePosition = e1PhyMibPortInfoAlarmTablePosition;
    entry->e1PhyMibPortInfoAlarmTablePort = e1PhyMibPortInfoAlarmTablePort;
    entry->e1PhyMibPortInfoAlarmTableE1Port = e1PhyMibPortInfoAlarmTableE1Port;
    entry->next = e1PhyMibPortInfoAlarmTable_head;
    e1PhyMibPortInfoAlarmTable_head = entry;
	e1PhyMibPortInfoAlarmTable_count++;

    return entry;
}

/* remove a row from the table */
void e1PhyMibPortInfoAlarmTable_removeEntry( struct e1PhyMibPortInfoAlarmTable_entry *entry ) {
    struct e1PhyMibPortInfoAlarmTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = e1PhyMibPortInfoAlarmTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        e1PhyMibPortInfoAlarmTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
	e1PhyMibPortInfoAlarmTable_count--;
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
e1PhyMibPortInfoAlarmTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = e1PhyMibPortInfoAlarmTable_head;
    return e1PhyMibPortInfoAlarmTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
e1PhyMibPortInfoAlarmTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct e1PhyMibPortInfoAlarmTable_entry *entry = (struct e1PhyMibPortInfoAlarmTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

	mutex_lock(lstlock);

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_IPADDRESS, entry->e1PhyMibPortInfoAlarmTablePosition );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->e1PhyMibPortInfoAlarmTablePort );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->e1PhyMibPortInfoAlarmTableE1Port );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;

		mutex_unlock(lstlock);
        return put_index_data;
    } else {
		mutex_unlock(lstlock);
        return NULL;
    }
}

int e1PhyMibPortInfoAlarmTable_compare(struct e1PhyMibPortInfoAlarmTable_entry *entry, in_addr_t po)
{
	if (!entry)
		return -1;

	if (entry->e1PhyMibPortInfoAlarmTablePosition == po)
		return 0;

	return -1;
}

DEFINE_TABLE_ENTRY_DELETE_FUNC(e1PhyMibPortInfoAlarmTable) 
DEFINE_TABLE_DELETE_FUNC(e1PhyMibPortInfoAlarmTable) 

struct e1PhyMibPortInfoAlarmTable_entry *e1PhyMibPortInfoAlarmTable_findEntry(in_addr_t po, int port, int num)
{
  	struct e1PhyMibPortInfoAlarmTable_entry	*entry = e1PhyMibPortInfoAlarmTable_head;

	while (entry) {
		if (entry->e1PhyMibPortInfoAlarmTablePosition == po &&
				entry->e1PhyMibPortInfoAlarmTablePort == port &&
				entry->e1PhyMibPortInfoAlarmTableE1Port == num) {
			return entry;
		}
		entry = entry->next;
	}

	return NULL;
}

void e1PhyMibPortInfoAlarmTable_updateEntry(struct e1PhyMibPortInfoAlarmTable_entry *entry, 
		in_addr_t po, int port, int num, nm_port_alarm *alarm, nm_port_stat *stat)
{
	unsigned long int tmp;

	entry->e1PhyMibPortInfoAlarmTablePosition  = po;
	entry->e1PhyMibPortInfoAlarmTablePort	   = port;
	entry->e1PhyMibPortInfoAlarmTableE1Port	   = num;

	tmp = alarm->r;
	entry->e1PhyMibPortInfoAlarmTableLOS	   = (tmp & ALARM_LOS) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableLOF	   = (tmp & ALARM_LOF) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableAIS	   = (tmp & ALARM_AIS) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableRAI	   = (tmp & ALARM_RAI) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableCASMFLOSS = (tmp & ALARM_CASMFLOSS) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableCRCMFLOSS = (tmp & ALARM_CRCMFLOSS) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableCASMFRAI  = (tmp & ALARM_CASMFRAI) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableOEQ       = (tmp & ALARM_OEQ) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableUEQ       = (tmp & ALARM_UEQ) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableJALT      = (tmp & ALARM_JALT) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableRESF      = (tmp & ALARM_RESF) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableRESEM     = (tmp & ALARM_RESEM) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableRSLIP     = (tmp & ALARM_RSLIP) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableRSL       = (tmp & ALARM_RSL_MASK ) >> ALARM_RSL_SHIFT;

	tmp = alarm->t;
	entry->e1PhyMibPortInfoAlarmTableTOC       = (tmp & ALARM_TOC) ? 1 : 0;
	entry->e1PhyMibPortInfoAlarmTableTSC       = (tmp & ALARM_TSC) ? 1 : 0;

	tmp = stat->lcvc;
	entry->e1PhyMibPortInfoAlarmTableCODE      = tmp;
	tmp = stat->pcvc;
	entry->e1PhyMibPortInfoAlarmTableCRC       = tmp;
	tmp = stat->fosc;
	entry->e1PhyMibPortInfoAlarmTableFAS       = tmp;
	tmp = stat->ebc;
	entry->e1PhyMibPortInfoAlarmTableEBIT      = tmp;
}

int e1PhyMibPortInfoAlarmTable_update(struct nm_lkaddr_info po, unsigned char *data) {
  	struct e1PhyMibPortInfoAlarmTable_entry	*entry = NULL;
	nm_port_alarm *al;
	nm_port_stat *st;
	in_addr_t position;	
	int maxport, port, num;
	int phycnt, pcnt;
	unsigned int i, j;
	
	if (e1PhyMibPortInfoAlarmTable_count >= E1PHYMAXITEMS) 
	{
		LOGERROR("E1Alarm:item over the max row %d", E1PHYMAXITEMS);
		return -1;
	}
	
	mutex_lock(lstlock);
	/* 1: delete board e1phyinfo  2: add new data */
	position = (po.rack << 24) | (po.shelf << 16) | (po.slot << 8) | po.subslot;
//	e1PhyMibPortInfoAlarmTable_delete(position);

	phycnt = data[0];
	pcnt = data[1];
	if (phycnt == 16 && pcnt == 8) {
		maxport = 8;
	}
	else {
		LOGERROR("E1PHY alarm stat update phycnt:%d,pcnt:%d wrong data.", phycnt, pcnt);
		return -1;
	}
	al = (nm_port_alarm *)&data[2];
	st = (nm_port_stat *)&data[sizeof(nm_port_alarm)*phycnt*pcnt+2];

	for (i = 0; i < maxport; i++) {
		port = i + 1;

		for(j = 0; j < 16; j++) {
			num = j + 1;
			entry = e1PhyMibPortInfoAlarmTable_findEntry(position, port, num);
			if (entry == NULL) {
				entry = e1PhyMibPortInfoAlarmTable_createEntry(position, port, num);
				if (!entry) {
					LOGERROR("%s: createEntry failed", __func__);
					return -1;
				}
			}
			e1PhyMibPortInfoAlarmTable_updateEntry(entry, position, port, num, al, st);
			al++;
			st++;
		}
    }

	mutex_unlock(lstlock);
	return 0;
}

DEFINE_TABLE_ENTRY_DELETE_INVALID_FUNC(e1PhyMibPortInfoAlarmTable) 

void e1PhyMibPortInfoAlarmTable_check_and_clear(void)
{
	struct e1PhyMibPortInfoAlarmTable_entry *entry = e1PhyMibPortInfoAlarmTable_head;
	struct nm_lkaddr_info po[SNMP_MAX_BOARD_CNT];
	int cnt = 0;
	in_addr_t position;
	int i;

	if (!entry)
		return;

	mutex_lock(lstlock);

	/* reset valid */
	while (entry) {
		entry->valid = 0;
		entry = entry->next;
	}

	/* get boards, and set valid */
	memset(po, 0, sizeof(po));
	cnt = boardsInfoTable_getboards(BOARD_TYPE_EIPB_V2, po);
	for (i = 0; i < cnt; i++) {
		position = (po[i].rack << 24) | (po[i].shelf << 16) | (po[i].slot << 8) | po[i].subslot;
		entry = e1PhyMibPortInfoAlarmTable_head;
		while (entry) {
			if (entry->e1PhyMibPortInfoAlarmTablePosition == position) {
				entry->valid = 1;
			}
			entry = entry->next;
		}
	}

	/* clear invalid */
	e1PhyMibPortInfoAlarmTable_head =
		e1PhyMibPortInfoAlarmTable_del_invalid_entrys(e1PhyMibPortInfoAlarmTable_head);

	mutex_unlock(lstlock);
}

void e1PhyMibPortInfoAlarmTable_clear(void)
{

	mutex_lock(lstlock);

	while (e1PhyMibPortInfoAlarmTable_head) {
		e1PhyMibPortInfoAlarmTable_removeEntry(e1PhyMibPortInfoAlarmTable_head);
	}

	e1PhyMibPortInfoAlarmTable_head = NULL;
	e1PhyMibPortInfoAlarmTable_count = 0;

	mutex_unlock(lstlock);
}


/** handles requests for the e1PhyMibPortInfoAlarmTable table */
int e1PhyMibPortInfoAlarmTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct e1PhyMibPortInfoAlarmTable_entry          *table_entry;

    DEBUGMSGTL(("e1PhyMibPortInfoAlarmTable:handler", "Processing request (%d)\n", reqinfo->mode));

	mutex_lock(lstlock);
    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct e1PhyMibPortInfoAlarmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(request);
    
            if ( !table_entry ) {
                continue;
            }
            switch (table_info->colnum) {
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEPOSITION:
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->e1PhyMibPortInfoAlarmTablePosition);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEPORT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTablePort);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEE1PORT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableE1Port);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLELOS:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableLOS);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLELOF:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableLOF);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEAIS:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableAIS);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLERAI:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableRAI);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLECASMFLOSS:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableCASMFLOSS);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLECRCMFLOSS:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableCRCMFLOSS);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLECASMFRAI:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableCASMFRAI);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEOEQ:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableOEQ);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEUEQ:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableUEQ);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEJALT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableJALT);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLERESF:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableRESF);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLERESEM:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableRESEM);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLERSLIP:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableRSLIP);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLERSL:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableRSL);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLETOC:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableTOC);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLETSC:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortInfoAlarmTableTSC);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLECODE:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->e1PhyMibPortInfoAlarmTableCODE);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLECRC:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->e1PhyMibPortInfoAlarmTableCRC);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEFAS:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->e1PhyMibPortInfoAlarmTableFAS);
                break;
            case COLUMN_E1PHYMIBPORTINFOALARMTABLEEBIT:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->e1PhyMibPortInfoAlarmTableEBIT);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }

	mutex_unlock(lstlock);
    return SNMP_ERR_NOERROR;
}
