/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "os.h"
#include "aplog.h"
#include "mutex.h"
#include "nm_typdef.h"
#include "bdtype.h"
#include "nmpkt.h"
#include "nm_glb.h"
#include "snmpcommon.h"
#include "phyadapt.h"
#include "nm_fpga.h"
#include "snmpMibModule.h"
#include "boardsInfoTable.h"
#include "e1PhyMibPortFlowStatTable.h"

    /* Typical data structure for a row entry */
struct e1PhyMibPortFlowStatTable_entry {
    /* Index values */
    in_addr_t e1PhyMibPortFlowStatPosition;
    long e1PhyMibPortFlowStatPort;

    /* Column values */
    u_long e1PhyMibPortFlowStatValue;

    /* Illustrate using a simple linked list */
    int   valid;
    struct e1PhyMibPortFlowStatTable_entry *next;
};

struct e1PhyMibPortFlowStatTable_entry  *e1PhyMibPortFlowStatTable_head = NULL;
static int e1PhyMibPortFlowStatTable_count = 0;
static void *lstlock = NULL;

/** Initializes the e1PhyMibPortFlowStatTable module */
void
init_e1PhyMibPortFlowStatTable(void)
{
	lstlock = mutex_open(NULL);
	if (lstlock == NULL) {
		LOGERROR("%s: mutex_open failed", __func__);
		return;
	}
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_e1PhyMibPortFlowStatTable();
}

void exit_e1PhyMibPortFlowStatTable(void)
{
	e1PhyMibPortFlowStatTable_clear();

	if (lstlock) 
		mutex_close(lstlock);
}

/** Initialize the e1PhyMibPortFlowStatTable table by defining its contents and how it's structured */
void
initialize_table_e1PhyMibPortFlowStatTable(void)
{
    const oid e1PhyMibPortFlowStatTable_oid[] = {1,3,6,1,4,1,8990,1,3,3};
    const size_t e1PhyMibPortFlowStatTable_oid_len   = OID_LENGTH(e1PhyMibPortFlowStatTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("e1PhyMibPortFlowStatTable:init", "initializing table e1PhyMibPortFlowStatTable\n"));

    reg = netsnmp_create_handler_registration(
              "e1PhyMibPortFlowStatTable",     e1PhyMibPortFlowStatTable_handler,
              e1PhyMibPortFlowStatTable_oid, e1PhyMibPortFlowStatTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_IPADDRESS,  /* index: e1PhyMibPortFlowStatPosition */
                           ASN_INTEGER,  /* index: e1PhyMibPortFlowStatPort */
                           0);
    table_info->min_column = COLUMN_E1PHYMIBPORTFLOWSTATPOSITION;
    table_info->max_column = COLUMN_E1PHYMIBPORTFLOWSTATVALUE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = e1PhyMibPortFlowStatTable_get_first_data_point;
    iinfo->get_next_data_point  = e1PhyMibPortFlowStatTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

/* create a new row in the (unsorted) table */
struct e1PhyMibPortFlowStatTable_entry *
e1PhyMibPortFlowStatTable_createEntry(in_addr_t  e1PhyMibPortFlowStatPosition,
                 long  e1PhyMibPortFlowStatPort) {
    struct e1PhyMibPortFlowStatTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct e1PhyMibPortFlowStatTable_entry);
    if (!entry)
        return NULL;

    entry->e1PhyMibPortFlowStatPosition = e1PhyMibPortFlowStatPosition;
    entry->e1PhyMibPortFlowStatPort = e1PhyMibPortFlowStatPort;
    entry->next = e1PhyMibPortFlowStatTable_head;
    e1PhyMibPortFlowStatTable_head = entry;
	e1PhyMibPortFlowStatTable_count++;

    return entry;
}

/* remove a row from the table */
void
e1PhyMibPortFlowStatTable_removeEntry( struct e1PhyMibPortFlowStatTable_entry *entry ) {
    struct e1PhyMibPortFlowStatTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = e1PhyMibPortFlowStatTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        e1PhyMibPortFlowStatTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
	e1PhyMibPortFlowStatTable_count--;
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
e1PhyMibPortFlowStatTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = e1PhyMibPortFlowStatTable_head;
    return e1PhyMibPortFlowStatTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
e1PhyMibPortFlowStatTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct e1PhyMibPortFlowStatTable_entry *entry = (struct e1PhyMibPortFlowStatTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

	mutex_lock(lstlock);

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_IPADDRESS, entry->e1PhyMibPortFlowStatPosition );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->e1PhyMibPortFlowStatPort );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
		mutex_unlock(lstlock);

        return put_index_data;
    } else {
		mutex_unlock(lstlock);
        return NULL;
    }
}

int e1PhyMibPortFlowStatTable_compare(struct e1PhyMibPortFlowStatTable_entry *entry, in_addr_t po)
{
	if (!entry)
		return -1;

	if (entry->e1PhyMibPortFlowStatPosition == po)
		return 0;

	return -1;
}

DEFINE_TABLE_ENTRY_DELETE_FUNC(e1PhyMibPortFlowStatTable) 
DEFINE_TABLE_DELETE_FUNC(e1PhyMibPortFlowStatTable) 

void e1PhyMibPortFlowStatTable_updateEntry(struct e1PhyMibPortFlowStatTable_entry *entry, 
		in_addr_t po, int port, unsigned int value)
{
	
	entry->e1PhyMibPortFlowStatPosition = po;
	entry->e1PhyMibPortFlowStatPort     = port;

	entry->e1PhyMibPortFlowStatValue    = value;
}

int e1PhyMibPortFlowStatTable_update(struct nm_lkaddr_info po, int bdtype, void *data)
{
	struct e1PhyMibPortFlowStatTable_entry *entry = e1PhyMibPortFlowStatTable_head;
	struct fpga_fstat *flow;
	in_addr_t position;	
	int port;
	unsigned int i;
	
	if (e1PhyMibPortFlowStatTable_count >= E1PHYMAXITEMS) 
	{
		LOGERROR("e1PhyFlowStat: item over the max row %d", E1PHYMAXITEMS);
		return -1;
	}
	
	mutex_lock(lstlock);
	/* 1: delete board sdhphyinfo 2: add new data */
	position = (po.rack << 24) | (po.shelf << 16) | (po.slot << 8) | po.subslot;
	e1PhyMibPortFlowStatTable_delete(position);

	if (bdtype == BOARD_TYPE_EIPB_V2) {
		flow = (struct fpga_fstat *)data;
		for (i = 0; i < flow->pcnt; i++) {
			port = i + 1;
			entry = e1PhyMibPortFlowStatTable_createEntry(position, port);
			if (!entry) {
				LOGERROR("%s: createEntry failed", __func__);
				continue;
			}
			e1PhyMibPortFlowStatTable_updateEntry(entry, position, port, flow->fsta[i].flow);
		}
	}

	mutex_unlock(lstlock);
	return 0;
}

DEFINE_TABLE_ENTRY_DELETE_INVALID_FUNC(e1PhyMibPortFlowStatTable) 

void e1PhyMibPortFlowStatTable_check_and_clear(void)
{
	struct e1PhyMibPortFlowStatTable_entry *entry = e1PhyMibPortFlowStatTable_head;
	struct nm_lkaddr_info po[SNMP_MAX_BOARD_CNT];
	int cnt = 0;
	in_addr_t position;
	int i;

	if (!entry)
		return;

	mutex_lock(lstlock);

	/* reset valid */
	while (entry) {
		entry->valid = 0;
		entry = entry->next;
	}

	/* get boards, and set valid */
	memset(po, 0, sizeof(po));
	cnt = boardsInfoTable_getboards(BOARD_TYPE_EIPB_V2, po);
	for (i = 0; i < cnt; i++) {
		position = (po[i].rack << 24) | (po[i].shelf << 16) | (po[i].slot << 8) | po[i].subslot;
		entry = e1PhyMibPortFlowStatTable_head;
		while (entry) {
			if (entry->e1PhyMibPortFlowStatPosition == position) {
				entry->valid = 1;
			}
			entry = entry->next;
		}
	}

	/* clear invalid */
	e1PhyMibPortFlowStatTable_head =
		e1PhyMibPortFlowStatTable_del_invalid_entrys(e1PhyMibPortFlowStatTable_head);

	mutex_unlock(lstlock);
}

void e1PhyMibPortFlowStatTable_clear(void)
{

	mutex_lock(lstlock);

	while (e1PhyMibPortFlowStatTable_head) {
		e1PhyMibPortFlowStatTable_removeEntry(e1PhyMibPortFlowStatTable_head);
	}

	e1PhyMibPortFlowStatTable_head = NULL;
	e1PhyMibPortFlowStatTable_count = 0;

	mutex_unlock(lstlock);
}

/** handles requests for the e1PhyMibPortFlowStatTable table */
int e1PhyMibPortFlowStatTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct e1PhyMibPortFlowStatTable_entry          *table_entry;

    DEBUGMSGTL(("e1PhyMibPortFlowStatTable:handler", "Processing request (%d)\n", reqinfo->mode));

	mutex_lock(lstlock);

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct e1PhyMibPortFlowStatTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
			if ( !table_entry ) {
				continue;
			}

            switch (table_info->colnum) {
            case COLUMN_E1PHYMIBPORTFLOWSTATPOSITION:
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->e1PhyMibPortFlowStatPosition);
                break;
            case COLUMN_E1PHYMIBPORTFLOWSTATPORT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->e1PhyMibPortFlowStatPort);
                break;
            case COLUMN_E1PHYMIBPORTFLOWSTATVALUE:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->e1PhyMibPortFlowStatValue);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }

	mutex_unlock(lstlock);
    return SNMP_ERR_NOERROR;
}
