/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef E1PHYMIBPORTINFOALARMTABLE_H
#define E1PHYMIBPORTINFOALARMTABLE_H

#include "nm_glb.h"

/* function declarations */
void init_e1PhyMibPortInfoAlarmTable(void);
void exit_e1PhyMibPortInfoAlarmTable(void);
void initialize_table_e1PhyMibPortInfoAlarmTable(void);
int e1PhyMibPortInfoAlarmTable_update(struct nm_lkaddr_info po, unsigned char *data);
int e1PhyMibPortInfoAlarmTable_delete(in_addr_t po);
void e1PhyMibPortInfoAlarmTable_check_and_clear(void);
void e1PhyMibPortInfoAlarmTable_clear(void);
Netsnmp_Node_Handler e1PhyMibPortInfoAlarmTable_handler;
Netsnmp_First_Data_Point  e1PhyMibPortInfoAlarmTable_get_first_data_point;
Netsnmp_Next_Data_Point   e1PhyMibPortInfoAlarmTable_get_next_data_point;

/* column number definitions for table e1PhyMibPortInfoAlarmTable */
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEPOSITION		1
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEPORT		2
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEE1PORT		3
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLELOS		4
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLELOF		5
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEAIS		6
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLERAI		7
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLECASMFLOSS		8
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLECRCMFLOSS		9
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLECASMFRAI		10
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEOEQ		11
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEUEQ		12
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEJALT		13
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLERESF		14
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLERESEM		15
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLERSLIP		16
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLERSL		17
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLETOC		18
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLETSC		19
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLECODE		20
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLECRC		21
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEFAS		22
       #define COLUMN_E1PHYMIBPORTINFOALARMTABLEEBIT		23
#endif /* E1PHYMIBPORTINFOALARMTABLE_H */
