/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "platform_info.h"

/** Initializes the platform_info module */
void
init_platform_info(void)
{
    const oid pltDevID_oid[] = { 1,3,6,1,4,1,8990,1,1,1 };
    const oid pltDevName_oid[] = { 1,3,6,1,4,1,8990,1,1,2 };
    const oid pltDevDscr_oid[] = { 1,3,6,1,4,1,8990,1,1,3 };
    const oid pltDevContact_oid[] = { 1,3,6,1,4,1,8990,1,1,4 };
    const oid pltDevPlatformType_oid[] = { 1,3,6,1,4,1,8990,1,1,5 };
    const oid pltDevShelfType_oid[] = { 1,3,6,1,4,1,8990,1,1,6 };
    const oid pltDevSnmpSoftwareVer_oid[] = { 1,3,6,1,4,1,8990,1,1,7 };

  DEBUGMSGTL(("platform_info", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevID", handle_pltDevID,
                               pltDevID_oid, OID_LENGTH(pltDevID_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevName", handle_pltDevName,
                               pltDevName_oid, OID_LENGTH(pltDevName_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevDscr", handle_pltDevDscr,
                               pltDevDscr_oid, OID_LENGTH(pltDevDscr_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevContact", handle_pltDevContact,
                               pltDevContact_oid, OID_LENGTH(pltDevContact_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevPlatformType", handle_pltDevPlatformType,
                               pltDevPlatformType_oid, OID_LENGTH(pltDevPlatformType_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevShelfType", handle_pltDevShelfType,
                               pltDevShelfType_oid, OID_LENGTH(pltDevShelfType_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("pltDevSnmpSoftwareVer", handle_pltDevSnmpSoftwareVer,
                               pltDevSnmpSoftwareVer_oid, OID_LENGTH(pltDevSnmpSoftwareVer_oid),
                               HANDLER_CAN_RONLY
        ));
}

static unsigned long long pltdevid = 0x41544341;

int
handle_pltDevID(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER64,
                                     &pltdevid/* XXX: a pointer to the scalar's data */,
                                     sizeof(pltdevid)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevID\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static char *pltdevname = "ATCA";

int
handle_pltDevName(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     pltdevname/* XXX: a pointer to the scalar's data */,
                                     strlen(pltdevname)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevName\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static char *pltdevdscr = "ATCA platform device";

int
handle_pltDevDscr(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     pltdevdscr/* XXX: a pointer to the scalar's data */,
                                     strlen(pltdevdscr)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevDscr\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static char *pltdevcontact = "www.hlytec.com";

int
handle_pltDevContact(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     pltdevcontact/* XXX: a pointer to the scalar's data */,
                                     strlen(pltdevcontact)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevContact\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/* 1: ATCA 2: MiroTCA 3: other */
static int pltdevtype = 1;

int
handle_pltDevPlatformType(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &pltdevtype/* XXX: a pointer to the scalar's data */,
                                     sizeof(pltdevtype)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevPlatformType\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

/* 1: 3U-2Slot 2: 4U-4Slot  3: 6U-6Slot */
static int pltdevshelftype = 3;

int
handle_pltDevShelfType(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &pltdevshelftype/* XXX: a pointer to the scalar's data */,
                                     sizeof(pltdevshelftype)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevShelfType\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static char *pltsnmpswver = "net-snmp version 5.8";

int
handle_pltDevSnmpSoftwareVer(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     pltsnmpswver/* XXX: a pointer to the scalar's data */,
                                     strlen(pltsnmpswver)/* XXX: the length of the data in bytes */);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_pltDevSnmpSoftwareVer\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

