/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PLATFORM_INFO_H
#define PLATFORM_INFO_H

/* function declarations */
void init_platform_info(void);
Netsnmp_Node_Handler handle_pltDevID;
Netsnmp_Node_Handler handle_pltDevName;
Netsnmp_Node_Handler handle_pltDevDscr;
Netsnmp_Node_Handler handle_pltDevContact;
Netsnmp_Node_Handler handle_pltDevPlatformType;
Netsnmp_Node_Handler handle_pltDevShelfType;
Netsnmp_Node_Handler handle_pltDevSnmpSoftwareVer;

#endif /* PLATFORM_INFO_H */
