/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SDHPHYMIBPORTFLOWSTATTABLE_H
#define SDHPHYMIBPORTFLOWSTATTABLE_H

#include "nm_glb.h"

/* function declarations */
void init_sdhPhyMibPortFlowStatTable(void);
void exit_sdhPhyMibPortFlowStatTable(void);
void initialize_table_sdhPhyMibPortFlowStatTable(void);
int sdhPhyMibPortFlowStatTable_update(struct nm_lkaddr_info po, int bdtype, void *data);
int sdhPhyMibPortFlowStatTable_delete(in_addr_t po);
void sdhPhyMibPortFlowStatTable_check_and_clear(void);
void sdhPhyMibPortFlowStatTable_clear(void);
Netsnmp_Node_Handler sdhPhyMibPortFlowStatTable_handler;
Netsnmp_First_Data_Point  sdhPhyMibPortFlowStatTable_get_first_data_point;
Netsnmp_Next_Data_Point   sdhPhyMibPortFlowStatTable_get_next_data_point;

/* column number definitions for table sdhPhyMibPortFlowStatTable */
       #define COLUMN_SDHPHYMIBPORTFLOWSTATPOSITION		1
       #define COLUMN_SDHPHYMIBPORTFLOWSTATPORT		2
       #define COLUMN_SDHPHYMIBPORTFLOWSTATVALUE		3
#endif /* SDHPHYMIBPORTFLOWSTATTABLE_H */
