/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "os.h"
#include "aplog.h"
#include "bdtype.h"
#include "mutex.h"
#include "nm_typdef.h"
#include "nmpkt.h"
#include "nm_glb.h"
#include "nm_fpga.h"
#include "snmpcommon.h"
#include "phyadapt.h"
#include "snmpMibModule.h"
#include "boardsInfoTable.h"
#include "sdhPhyMibPortInfoAlarmTable.h"

    /* Typical data structure for a row entry */
struct sdhPhyMibPortInfoAlarmTable_entry {
    /* Index values */
    in_addr_t sdhPhyMibPortInfoAlarmTablePosition;
    long sdhPhyMibPortInfoAlarmTablePort;

    /* Column values */
    long sdhPhyMibPortInfoAlarmTableLOS;
    long sdhPhyMibPortInfoAlarmTableLOF;
    long sdhPhyMibPortInfoAlarmTableSTM1;
    long sdhPhyMibPortInfoAlarmTableE1CNT;
    u_long sdhPhyMibPortInfoAlarmTableSIG64KCHCNT;
    u_long sdhPhyMibPortInfoAlarmTableSIG64KFRCNT;
    u_long sdhPhyMibPortInfoAlarmTableSIG2MCHCNT;
    u_long sdhPhyMibPortInfoAlarmTableSIG2MFRCNT;

    /* Illustrate using a simple linked list */
    int   valid;
    struct sdhPhyMibPortInfoAlarmTable_entry *next;
};

struct sdhPhyMibPortInfoAlarmTable_entry  *sdhPhyMibPortInfoAlarmTable_head = NULL;
static int sdhPhyMibPortInfoAlarmTable_count = 0;
static void *lstlock = NULL;

/** Initializes the sdhPhyMibPortInfoAlarmTable module */
void init_sdhPhyMibPortInfoAlarmTable(void)
{
	lstlock = mutex_open(NULL);
	if (lstlock == NULL) {
		LOGERROR("%s: mutex_open failed", __func__);
		return;
	}
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_sdhPhyMibPortInfoAlarmTable();
}

void exit_sdhPhyMibPortInfoAlarmTable(void)
{
	sdhPhyMibPortInfoAlarmTable_clear();

	if (lstlock) 
		mutex_close(lstlock);
}

/** Initialize the sdhPhyMibPortInfoAlarmTable table by defining its contents and how it's structured */
void
initialize_table_sdhPhyMibPortInfoAlarmTable(void)
{
    const oid sdhPhyMibPortInfoAlarmTable_oid[] = {1,3,6,1,4,1,8990,1,4,1};
    const size_t sdhPhyMibPortInfoAlarmTable_oid_len   = OID_LENGTH(sdhPhyMibPortInfoAlarmTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("sdhPhyMibPortInfoAlarmTable:init", "initializing table sdhPhyMibPortInfoAlarmTable\n"));

    reg = netsnmp_create_handler_registration(
              "sdhPhyMibPortInfoAlarmTable",     sdhPhyMibPortInfoAlarmTable_handler,
              sdhPhyMibPortInfoAlarmTable_oid, sdhPhyMibPortInfoAlarmTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_IPADDRESS,  /* index: sdhPhyMibPortInfoAlarmTablePosition */
                           ASN_INTEGER,  /* index: sdhPhyMibPortInfoAlarmTablePort */
                           0);
    table_info->min_column = COLUMN_SDHPHYMIBPORTINFOALARMTABLEPOSITION;
    table_info->max_column = COLUMN_SDHPHYMIBPORTINFOALARMTABLESIG2MFRCNT;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = sdhPhyMibPortInfoAlarmTable_get_first_data_point;
    iinfo->get_next_data_point  = sdhPhyMibPortInfoAlarmTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

/* create a new row in the (unsorted) table */
struct sdhPhyMibPortInfoAlarmTable_entry *
sdhPhyMibPortInfoAlarmTable_createEntry(
                 in_addr_t  sdhPhyMibPortInfoAlarmTablePosition,
                 long  sdhPhyMibPortInfoAlarmTablePort) {
    struct sdhPhyMibPortInfoAlarmTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct sdhPhyMibPortInfoAlarmTable_entry);
    if (!entry)
        return NULL;

    entry->sdhPhyMibPortInfoAlarmTablePosition = sdhPhyMibPortInfoAlarmTablePosition;
    entry->sdhPhyMibPortInfoAlarmTablePort = sdhPhyMibPortInfoAlarmTablePort;
    entry->next = sdhPhyMibPortInfoAlarmTable_head;
    sdhPhyMibPortInfoAlarmTable_head = entry;
	sdhPhyMibPortInfoAlarmTable_count++;

    return entry;
}

/* remove a row from the table */
void
sdhPhyMibPortInfoAlarmTable_removeEntry( struct sdhPhyMibPortInfoAlarmTable_entry *entry ) {
    struct sdhPhyMibPortInfoAlarmTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = sdhPhyMibPortInfoAlarmTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        sdhPhyMibPortInfoAlarmTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
	sdhPhyMibPortInfoAlarmTable_count--;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
sdhPhyMibPortInfoAlarmTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = sdhPhyMibPortInfoAlarmTable_head;
    return sdhPhyMibPortInfoAlarmTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
sdhPhyMibPortInfoAlarmTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct sdhPhyMibPortInfoAlarmTable_entry *entry = (struct sdhPhyMibPortInfoAlarmTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

	mutex_lock(lstlock);

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_IPADDRESS, entry->sdhPhyMibPortInfoAlarmTablePosition );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->sdhPhyMibPortInfoAlarmTablePort );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
		mutex_unlock(lstlock);

        return put_index_data;
    } else {
		mutex_unlock(lstlock);
        return NULL;
    }
}

int sdhPhyMibPortInfoAlarmTable_compare(struct sdhPhyMibPortInfoAlarmTable_entry *entry, in_addr_t po)
{
	if (!entry)
		return -1;

	if (entry->sdhPhyMibPortInfoAlarmTablePosition == po)
		return 0;

	return -1;
}

DEFINE_TABLE_ENTRY_DELETE_FUNC(sdhPhyMibPortInfoAlarmTable) 
DEFINE_TABLE_DELETE_FUNC(sdhPhyMibPortInfoAlarmTable) 

void sdhPhyMibPortInfoAlarmTable_updateEntry(struct sdhPhyMibPortInfoAlarmTable_entry *entry, 
		in_addr_t po, int port, struct fpga_port_status *ptr)
{
	
	entry->sdhPhyMibPortInfoAlarmTablePosition = po;
	entry->sdhPhyMibPortInfoAlarmTablePort     = port;

	entry->sdhPhyMibPortInfoAlarmTableLOS      = ptr->los;
	entry->sdhPhyMibPortInfoAlarmTableLOF      = ptr->lof;
	entry->sdhPhyMibPortInfoAlarmTableSTM1     = ptr->stm1;
	entry->sdhPhyMibPortInfoAlarmTableE1CNT    = ptr->e1cnt;
	entry->sdhPhyMibPortInfoAlarmTableSIG64KCHCNT = ptr->sig64kchcnt;
	entry->sdhPhyMibPortInfoAlarmTableSIG64KFRCNT = ptr->sig64kchcnt;
	entry->sdhPhyMibPortInfoAlarmTableSIG2MCHCNT  = ptr->sig2mchcnt;
	entry->sdhPhyMibPortInfoAlarmTableSIG2MFRCNT  = ptr->sig2mfrcnt;
}

int sdhPhyMibPortInfoAlarmTable_update(struct nm_lkaddr_info po, int bdtype, void *data)
{
	struct sdhPhyMibPortInfoAlarmTable_entry *entry = sdhPhyMibPortInfoAlarmTable_head;
	struct fpga_status *sdhps;
	in_addr_t position;	
	int port;
	unsigned int i;
	
	if (sdhPhyMibPortInfoAlarmTable_count >= SDHPHYMAXITEMS) 
	{
		LOGERROR("sdhphyalarm:item over the max row %d", SDHPHYMAXITEMS);
		return -1;
	}
	
	mutex_lock(lstlock);
	/* 1: delete board sdhphyinfo 2: add new data */
	position = (po.rack << 24) | (po.shelf << 16) | (po.slot << 8) | po.subslot;
#if 0
	while (entry) {
		if (entry->sdhPhyMibPortInfoAlarmTablePosition == position) {
			sdhPhyMibPortInfoAlarmTable_removeEntry(entry);
		}
		entry = entry->next;
	}
#else
	sdhPhyMibPortInfoAlarmTable_delete(position);
#endif

	sdhps = (struct fpga_status *)data;
	for (i = 0; i < sdhps->pcnt; i++) {
		port = i + 1;
		entry = sdhPhyMibPortInfoAlarmTable_createEntry(position, port);
		if (!entry) {
			LOGERROR("%s: createEntry failed", __func__);
			continue;
		}
		sdhPhyMibPortInfoAlarmTable_updateEntry(entry, position, port, &sdhps->st[i]);
	}

	mutex_unlock(lstlock);
	return 0;
}

DEFINE_TABLE_ENTRY_DELETE_INVALID_FUNC(sdhPhyMibPortInfoAlarmTable) 

void sdhPhyMibPortInfoAlarmTable_check_and_clear(void)
{
	struct sdhPhyMibPortInfoAlarmTable_entry *entry = sdhPhyMibPortInfoAlarmTable_head;
	struct nm_lkaddr_info po[SNMP_MAX_BOARD_CNT];
	int cnt = 0;
	in_addr_t position;
	int i;

	if (!entry)
		return;

	mutex_lock(lstlock);

	/* reset valid */
	while (entry) {
		entry->valid = 0;
		entry = entry->next;
	}

	/* get boards, and set valid */
	memset(po, 0, sizeof(po));
	cnt = boardsInfoTable_getboards(BOARD_TYPE_OI_AMC_V3, po);
	for (i = 0; i < cnt; i++) {
		position = (po[i].rack << 24) | (po[i].shelf << 16) | (po[i].slot << 8) | po[i].subslot;
		entry = sdhPhyMibPortInfoAlarmTable_head;
		while (entry) {
			if (entry->sdhPhyMibPortInfoAlarmTablePosition == position) {
				entry->valid = 1;
			}
			entry = entry->next;
		}
	}

	/* clear invalid */
	sdhPhyMibPortInfoAlarmTable_head =
		sdhPhyMibPortInfoAlarmTable_del_invalid_entrys(sdhPhyMibPortInfoAlarmTable_head);

	mutex_unlock(lstlock);
}

void sdhPhyMibPortInfoAlarmTable_clear(void)
{

	mutex_lock(lstlock);

	while (sdhPhyMibPortInfoAlarmTable_head) {
		sdhPhyMibPortInfoAlarmTable_removeEntry(sdhPhyMibPortInfoAlarmTable_head);
	}

	sdhPhyMibPortInfoAlarmTable_head = NULL;
	sdhPhyMibPortInfoAlarmTable_count = 0;

	mutex_unlock(lstlock);
}

/** handles requests for the sdhPhyMibPortInfoAlarmTable table */
int
sdhPhyMibPortInfoAlarmTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct sdhPhyMibPortInfoAlarmTable_entry          *table_entry;

    DEBUGMSGTL(("sdhPhyMibPortInfoAlarmTable:handler", "Processing request (%d)\n", reqinfo->mode));

	mutex_lock(lstlock);

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sdhPhyMibPortInfoAlarmTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(request);
    
            if ( !table_entry ) {
                continue;
            }
            switch (table_info->colnum) {
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLEPOSITION:
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->sdhPhyMibPortInfoAlarmTablePosition);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLEPORT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sdhPhyMibPortInfoAlarmTablePort);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLELOS:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableLOS);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLELOF:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableLOF);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLESTM1:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableSTM1);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLEE1CNT:
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableE1CNT);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLESIG64KCHCNT:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableSIG64KCHCNT);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLESIG64KFRCNT:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableSIG64KFRCNT);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLESIG2MCHCNT:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableSIG2MCHCNT);
                break;
            case COLUMN_SDHPHYMIBPORTINFOALARMTABLESIG2MFRCNT:
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->sdhPhyMibPortInfoAlarmTableSIG2MFRCNT);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }

	mutex_unlock(lstlock);

    return SNMP_ERR_NOERROR;
}
