/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SWITCHMIBPORTINFOSTATTABLE_H
#define SWITCHMIBPORTINFOSTATTABLE_H

#include "nm_glb.h"

/* function declarations */
void init_switchMibPortInfoStatTable(void);
void exit_switchMibPortInfoStatTable(void);
void initialize_table_switchMibPortInfoStatTable(void);
int switchMibPortInfoStatTable_update(struct nm_lkaddr_info po, int cnt, void *data);
int switchMibPortInfoStatTable_delete(in_addr_t po);
void switchMibPortInfoStatTable_check_and_clear(void);
void switchMibPortInfoStatTable_clear(void);
Netsnmp_Node_Handler switchMibPortInfoStatTable_handler;
Netsnmp_First_Data_Point  switchMibPortInfoStatTable_get_first_data_point;
Netsnmp_Next_Data_Point   switchMibPortInfoStatTable_get_next_data_point;

/* column number definitions for table switchMibPortInfoStatTable */
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLEPOSITION		1
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLEPORT    		2
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLEPORTNAME		3
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLELINKSTATE		4
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLELINKENABLE		5
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLEAUTONEG		6
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLELINKSPEED		7
       #define COLUMN_SWITCHMIBPORTINFOSTATTABLEDUPLEX		8
#endif /* SWITCHMIBPORTINFOSTATTABLE_H */
