#
# (C) Copyright 2007-2010
# Hu Chunlin <chunlin.hu@gmail.com>
#
# Makefile - To make my life easier.
#

SUBDIRS = fpgadrv fpgamif_lib lkmp_lib esnapp svcapp nmboard_lib psagent psagent_lkmp scripts

include $(CURDIR)/../../dirs.mk

