#
# (C) Copyright 2007-2010
# Hu Chunlin <chunlin.hu@gmail.com>
#
# Makefile - To make my life easier.
#

SUBDIRS = include aplog mm util apframe adapter cgiparse cmdsvr psp psp_lkmp

include $(CURDIR)/../dirs.mk

